The dataset is collected from the 1994 Census database and contains income data.
Data Information:
```
    age: continuous.
    workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
    fnlwgt: continuous.
    education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
    education-num: continuous.
    marital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
    occupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
    relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
    race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
    sex: Female, Male.
    capital-gain: continuous.
    capital-loss: continuous.
    hours-per-week: continuous.
    native-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.
    salary: >50K,<=50K
```
Perform data analysis using Pandas by completing the assigned tasks.

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("./data/adult.data.csv")
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

1. Count how many men and women (feature sex) are represented in this dataset.

In [5]:
gender = df.value_counts('sex')
gender

sex
Male      21790
Female    10771
Name: count, dtype: int64

2. What is the average age of men (feature age) across the entire dataset?

In [6]:
avg_age = df[df['sex'] == 'Male']['age'].mean()
avg_age

np.float64(39.43354749885268)

3. What is the proportion of United States citizens (feature native-country)?

In [7]:
natives_prop = df[df["native-country"]=="United-States"].value_counts("native-country") / len(df)
print(f"Proportion: {natives_prop.iloc[0]*100:.2f}%")

Proportion: 89.59%

**4-5. Calculate the mean and standard deviation of age for those who earn more than 50K per year (feature *salary*) and those who earn less than 50K per year.**

In [8]:
less_than_50k = df[df['salary'] == '<=50K']
more_than_50k = df[df['salary'] == '>50K']
less_than_50k_age_std = less_than_50k['age'].std()
less_than_50k_age_mean = less_than_50k['age'].mean()
more_than_50k_age_std = more_than_50k['age'].std()
more_than_50k_age_mean = more_than_50k['age'].mean()
print(f"Less than 50k age mean: {less_than_50k_age_mean:.2f}")
print(f"Less than 50k age std: {less_than_50k_age_std:.2f}")
print(f"More than 50k age mean: {more_than_50k_age_mean:.2f}")
print(f"More than 50k age std: {more_than_50k_age_std:.2f}")

Less than 50k age mean: 36.78
Less than 50k age std: 14.02
More than 50k age mean: 44.25
More than 50k age std: 10.52

6. Is it true that people who earn more than 50k have at least a higher education? (feature education – Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters or Doctorate)

In [9]:
higher_edu = ["Bachelors", "Prof-school", "Assoc-acdm", "Assoc-voc", "Masters", "Doctorate"]
education = df[df["education"].isin(higher_edu)].groupby(by=["education", "salary"])['age'].count()
education
# It is not true, that people who earn more than 50k have at least a higher education.
# However we can see the trend, that if a person has a higher education level,
# then this person has a higher likelihood of getting paid more.
# To draw a better conclusion we need a sample with higher population.

education    salary
Assoc-acdm   <=50K      802
             >50K       265
Assoc-voc    <=50K     1021
             >50K       361
Bachelors    <=50K     3134
             >50K      2221
Doctorate    <=50K      107
             >50K       306
Masters      <=50K      764
             >50K       959
Prof-school  <=50K      153
             >50K       423
Name: age, dtype: int64

7. Display age statistics for each race (feature *race*) and gender. Use *groupby* and *describe*. In this way, find the maximum age of men of the *Asian-Pac-Islander* race.

In [10]:
age_stats = df.groupby(by=["race", "sex"])['age'].describe()
print(age_stats)
max_age = age_stats.loc[('Asian-Pac-Islander', 'Male')]['max']
print(max_age)

                             count       mean        std   min   25%   50%  \
race               sex
Amer-Indian-Eskimo Female    119.0  37.117647  13.114991  17.0  27.0  36.0
                   Male      192.0  37.208333  12.049563  17.0  28.0  35.0
Asian-Pac-Islander Female    346.0  35.089595  12.300845  17.0  25.0  33.0
                   Male      693.0  39.073593  12.883944  18.0  29.0  37.0
Black              Female   1555.0  37.854019  12.637197  17.0  28.0  37.0
                   Male     1569.0  37.682600  12.882612  17.0  27.0  36.0
Other              Female    109.0  31.678899  11.631599  17.0  23.0  29.0
                   Male      162.0  34.654321  11.355531  17.0  26.0  32.0
White              Female   8642.0  36.811618  14.329093  17.0  25.0  35.0
                   Male    19174.0  39.652498  13.436029  17.0  29.0  38.0

                             75%   max
race               sex
Amer-Indian-Eskimo Female  46.00  80.0
                   Male    45.00  82.0
Asian-Pac-Islander Female  43.75  75.0
                   Male    46.00  90.0
Black              Female  46.00  90.0
                   Male    46.00  90.0
Other              Female  39.00  74.0
                   Male    42.00  77.0
White              Female  46.00  90.0
                   Male    49.00  90.0
90.0

8. Among whom is the proportion of high earners (>50K) greater among married or single men (feature *marital-status*)? Married individuals are considered those whose *marital-status* begins with *Married* (Married-civ-spouse, Married-spouse-absent, or Married-AF-spouse); the rest are considered single.

In [11]:
high_earners = df[df['salary'].isin(['>50K']) &
                  df["sex"].isin(["Male"])].copy()
high_earners["marital-status"] = high_earners["marital-status"].apply(lambda x: "Married" if x.startswith("Married") else "Single")
high_earners = high_earners.groupby(by="marital-status")['age'].count()
high_earners = high_earners.rename('proportion')
high_earners_prop = high_earners / high_earners.sum()
high_earners_prop

marital-status
Married    0.895377
Single     0.104623
Name: proportion, dtype: float64

9. What is the maximum number of hours a person works per week (feature *hours-per-week*)? How many people work that many hours, and what percentage of them earn a lot (>50K)?

In [12]:
max_working_hours = df['hours-per-week'].max()
print(f"Max working hours: {max_working_hours}")
max_working_hours_people = df[df['hours-per-week'] == max_working_hours].groupby(by="salary").count()["age"]
max_working_hours_people_prop = max_working_hours_people / max_working_hours_people.sum()
max_working_hours_people_prop

Max working hours: 99

salary
<=50K    0.705882
>50K     0.294118
Name: age, dtype: float64

10. Calculate the average working hours (*hours-per-week*) for low and high earners (*salary*) for each country (*native-country*).

In [13]:
average_hours_per_country_salary = df.groupby(['native-country', 'salary'])['hours-per-week'].mean().unstack()
print(average_hours_per_country_salary)

salary                          <=50K       >50K
native-country
?                           40.164760  45.547945
Cambodia                    41.416667  40.000000
Canada                      37.914634  45.641026
China                       37.381818  38.900000
Columbia                    38.684211  50.000000
Cuba                        37.985714  42.440000
Dominican-Republic          42.338235  47.000000
Ecuador                     38.041667  48.750000
El-Salvador                 36.030928  45.000000
England                     40.483333  44.533333
France                      41.058824  50.750000
Germany                     39.139785  44.977273
Greece                      41.809524  50.625000
Guatemala                   39.360656  36.666667
Haiti                       36.325000  42.750000
Holand-Netherlands          40.000000        NaN
Honduras                    34.333333  60.000000
Hong                        39.142857  45.000000
Hungary                     31.300000  50.000000
India                       38.233333  46.475000
Iran                        41.440000  47.500000
Ireland                     40.947368  48.000000
Italy                       39.625000  45.400000
Jamaica                     38.239437  41.100000
Japan                       41.000000  47.958333
Laos                        40.375000  40.000000
Mexico                      40.003279  46.575758
Nicaragua                   36.093750  37.500000
Outlying-US(Guam-USVI-etc)  41.857143        NaN
Peru                        35.068966  40.000000
Philippines                 38.065693  43.032787
Poland                      38.166667  39.000000
Portugal                    41.939394  41.500000
Puerto-Rico                 38.470588  39.416667
Scotland                    39.444444  46.666667
South                       40.156250  51.437500
Taiwan                      33.774194  46.800000
Thailand                    42.866667  58.333333
Trinadad&Tobago             37.058824  40.000000
United-States               38.799127  45.505369
Vietnam                     37.193548  39.200000
Yugoslavia                  41.600000  49.500000

11. Group people by age groups *young*, *adult*, *retiree*, where:
* *young* corresponds to 16-35 years
* *adult* - 35-70 years
* *retiree* - 70-100 years

Assign the name of the corresponding group for each person to a new column `AgeGroup`.

In [14]:
ages = [16, 35, 70, 101]
labels = ['young', 'adult', 'retiree']
df['AgeGroup'] = pd.cut(df['age'], bins=ages, labels=labels, right=False)
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary,AgeGroup
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K,adult
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,adult
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,adult
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,adult
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K,young

12-13. Determine the number of people earning >50K in each age group (AgeGroup column), and also output the name of the age group in which people more often earn more than 50K (>50K).

In [15]:
age_group_salary_counts = df.groupby(['AgeGroup', 'salary'])['age'].count()
print(age_group_salary_counts.loc[(slice(None), '>50K')])
total_per_age_group = df.groupby('AgeGroup')['age'].count()
high_earners_per_age_group = age_group_salary_counts.loc[(slice(None), '>50K')]
proportion_high_earners = high_earners_per_age_group / total_per_age_group
print(proportion_high_earners)
age_group_most_high_earners = proportion_high_earners.dropna().idxmax()
print(age_group_most_high_earners)

AgeGroup
young      1488
adult      6240
retiree     113
Name: age, dtype: int64
AgeGroup
young      0.105915
adult      0.348935
retiree    0.179650
Name: age, dtype: float64
adult

/tmp/ipython-input-181064897.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  age_group_salary_counts = df.groupby(['AgeGroup', 'salary'])['age'].count()
/tmp/ipython-input-181064897.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  total_per_age_group = df.groupby('AgeGroup')['age'].count()

14. Group people by employment type (occupation column) and determine the number of people in each group. Then write a filtering function `filter_func` that will return only those groups in which the average age (age column) is not more than 40 and in which all workers work more than 5 hours per week (hours-per-week column).

In [16]:
employment = df.groupby(by="occupation")['age'].count()
def filter_func(employment: pd.DataFrame) -> pd.DataFrame:
  avg_age_by_employment = (df.groupby(by="occupation")["age"].mean() < 40)
  avg_hours_by_employment = (df.groupby(by="occupation")["hours-per-week"].mean() > 5)
  return employment[avg_age_by_employment & avg_hours_by_employment]
print(filter_func(employment))

occupation
Adm-clerical         3770
Armed-Forces            9
Craft-repair         4099
Handlers-cleaners    1370
Machine-op-inspct    2002
Other-service        3295
Protective-serv       649
Sales                3650
Tech-support          928
Name: age, dtype: int64